### ISSUE TITLE
DHCP: REQUEST should send the `ServerId` (option 54) for dnsmasq

### ISSUE THREAD

**Issue by birkenfeld** [newAM/w5500-rs#249]
### Describe the Problem

Trying to get DHCP working with my local network where the PC is running dnsmasq, I saw DISCOVER, OFFER, and REQUEST on the wire but dnsmasq wouldn't react to the latter.

After debugging a while and comparing the DHCP packets to those from other devices, the reason seems to be that this library doesn't send the `ServerId` option (54) in the DHCPREQUEST message. I hacked that in and got a DHCPACK.  (Will make a PR soon.)

#### Expected Behaviour

Device gets an IP assigned.

### Steps to Reproduce

Run the `ambientsensor` or similar example on a network with dnsmasq (here version 2.89)

### Logging

Can be provided if needed.

**Comment by zer0-droids** [comment]
Hello,

I would like to reopen this Issue, because the REQUEST message sent by my device is NACK'ed by my server. The ServerID option seems to be incorrect. Please see PR #268.
Or should I open a new Issue?

Thanks
